### ISSUE TITLE
Use without shortcode

### ISSUE THREAD

**Issue by pattyland** [cuny-academic-commons/google-docs-shortcode#3]
Hey,

could you enable the use without the shortcode? Just replace the Google Docs link with the equivalent embedding code!

Greets, Sören

**Comment by r-a-y** [comment]
v0.4 now includes [Shortcake](https://wordpress.org/plugins/shortcode-ui) support, which should make this easier to use.

Please install Shortcake alongside Google Docs Shortcode.  Then, when creating a post, click on **Add Media > Insert Post Element > Google Drive**.

Going to close this one.
