### ISSUE TITLE
Not working with latest version of spreadsheets

### ISSUE THREAD

**Issue by daltonrooney** [cuny-academic-commons/google-docs-shortcode#4]
Hey, I posted this on the WP forum, but thought you might catch it quicker if I also posted here. The plugin isn't working for me with spreadsheets because of the hard-coded path '/spreadsheet/' on line 65. The new Google doc link has a path of '/spreadsheets/', so the shortcode does not return any content. Thanks for a nice, simple plugin.

**Comment by chedbowls** [comment]
I have the same problem. Has this been resolved?
