### ISSUE TITLE
width paramater not respected

### ISSUE THREAD

**Issue by d9748336** [cuny-academic-commons/google-docs-shortcode#5]
Any chance I could force the width beyond the standard theme setting?

**Comment by r-a-y** [comment]
@d9748336 - Apologies for the extremely late reply!

I couldn't duplicate this with a Google Slide and a width that I set in the shortcode.

eg. `[gdoc link="LINK" width="200"]`

How are you using the shortcode?

**Comment by r-a-y** [comment]
Going to close this for now.

Please feel free to reopen if you are still encountering issues with this.
