### ISSUE TITLE
Add "Add Header and Footer" Option in Shortcake Modal 

### ISSUE THREAD

**Issue by mrjarbenne** [cuny-academic-commons/google-docs-shortcode#9]
Could the "Add Header and Footer" option be added to the Google Drive Details Shortcake interface. It's an initial option in the https://github.com/hwdsbcommons/gdrive plugin: 

![2015-10-15_20-12-06](https://cloud.githubusercontent.com/assets/480667/10530814/237ccbfc-7379-11e5-9c98-c6360a2b3d4f.png)

But in cases where the user forgets to add this, it's absent from the edit menu created through the ShortCake interface: 

![2015-10-15_20-06-05](https://cloud.githubusercontent.com/assets/480667/10530853/5ae1c1f6-7379-11e5-9e22-5e1d3ac6e993.png)

**Comment by r-a-y** [comment]
The header / footer option is in the code.

I believe it's a bug with Shortcake's checkbox functionality.  I might 
switch out the checkbox with a <select> dropdown instead to see if that 
works.

**Comment by r-a-y** [comment]
@mrjarbenne - After doing some more research, the header / footer option is only available to published documents (through "File > Publish to the web"), not link-shared documents.(invoked through "Anyone with the link" or "Public on the Web").

I guess that's why I commented it out in Shortcake.

**Comment by mrjarbenne** [comment]
Thanks for the clarification. :+1:

**Comment by r-a-y** [comment]
I'm going to add this back with better detection for published documents.
